# Changes here will be overwritten by Copier
_commit: c9a674b
_src_path: gh:browniebroke/pypackage-template
add_me_as_contributor: true
copyright_year: '2025'
documentation: true
email: mark@securehst.com
full_name: Mark Moreno
github_username: markm-io
has_cli: false
initial_commit: true
is_django_package: false
open_source_license: MIT
package_name: slack_webhook_notifier
project_name: Slack Webhook Notifier
project_short_description: This package helps monitor automation processes with real-time
    updates directly in Slack.
project_slug: slack-webhook-notifier
run_uv_sync: true
setup_github: true
setup_pre_commit: true

